### ISSUE TITLE
Body is not printed out

### ISSUE THREAD

**Issue by justinmchase** [kennship/http-echo#2]
I could be wrong but it seems like this is failing to echo the body of requests back:

This line here:
https://github.com/kennship/http-echo/blob/master/index.js#L10

I believe this function should include the `body-parser` module to properly handle the incoming request body. At least:

```js
var express = require('express')
var bodyParser = require('body-parser') 

var app = express()
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())

app.all('*', (req, res) => {
  res.json({
    service: process.env.SERVICE_NAME || undefined, // Keys with value `undefined` are omitted during JSON serialization
    path: req.path,
    headers: req.headers,
    method: req.method,
    body: req.body,
    cookies: req.cookies,
    fresh: req.fresh,
    hostname: req.hostname,
    ip: req.ip,
    ips: req.ips,
    protocol: req.protocol,
    query: req.query,
    subdomains: req.subdomains,
    xhr: req.xhr,
  })
})

app.listen(process.env.PORT || 3000)
```

Thoughts? I can put together a PR if that would help.

**Comment by ryaninvents** [comment]
Good catch! This would select the parser based on `Content-Type`, right? I'd gladly accept a PR for this 🙂

**Comment by justinmchase** [comment]
Yes I believe it does that and adds a few implementations for common content-types. I'll cook it up soon.
